### ISSUE TITLE
duration is not working on Windows 11 Pro 22623.1037

### ISSUE THREAD

**Issue by Rothammel** [LAB02-Admin/HASS.Agent-Docs#4]
Hi,

I have tried some different duration values, but it's not working.

```
service: notify.surface
data:
  message: huhu Fay ist online
  title: Twitch starten
  data:
    duration: 60
```
